name: $(Date:yyyyMMdd)-$(Rev:rrr)

trigger:
- master

resources:
- repo: self

parameters:
- name: PushImage
  displayName: Push image to container registry
  type: boolean
  default: false
- name: IsRelease
  displayName: Release candidate
  type: boolean
  default: false
- name: PublicUrl
  displayName: Public URL for React
  type: string
  default: ""

variables:
  Version: 1.0.0
  IsMaster: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}

jobs:  
- job: Build
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
      echo "IsMaster: $IsMaster"
      echo "Version: $Version"
      echo "IsRelease: $IsRelease"
      ImageTag="$Version-beta"
      if [[ ${IsMaster,,} = "false" ]]; then
        ImageTag="$Version-build-$BuildNumber"
      elif [ ${IsRelease,,} = "true" ]; then
        ImageTag="$Version"
      fi
      echo "ImageTag: $ImageTag"
      echo "##vso[task.setvariable variable=ImageTag]$ImageTag"
    displayName: Compute image tag
    env:
      BuildNumber: $(Build.BuildNumber)
      IsMaster: $(IsMaster)
      Version: $(Version)
      IsRelease: $(IsRelease)
  
  - template: azure-pipelines-build.yml
    parameters:
      containerRegistryServiceConnection: DockerHub
      repository: poveilleux/azure-file-share-explorer
      pushCondition: and(succeeded(), eq(variables['PushImage'], true))
      imageTag: $(ImageTag)
