name: $(Date:yyyyMMdd)-$(Rev:rrr)

trigger:
- master

resources:
- repo: self

variables:
  version: 0.0.1

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "IsMaster: $IsMaster"
        echo "Version: $Version"
        ImageTag="$Version-beta"
        if [[ $IsMaster = "False" ]]; then
          ImageTag="$Version-build-$BuildNumber"
        fi
        echo "##vso[task.setvariable variable=ImageTag]$ImageTag"
        echo "ImageTag: $ImageTag"
      displayName: Compute image tag
      env:
        BuildNumber: $(Build.BuildNumber)
        IsMaster: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}
        Version: $(version)

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        tags: |
          $(ImageTag)

    - task: Docker@2
      displayName: Push to Docker Hub
      enabled: false
      inputs:
        command: push
        tags: $(ImageTag)
