trigger:
- master

resources:
- repo: self

variables:
  version: 0.0.1
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "IsBeta: $IsBeta"
        echo "Version: $Version"
        ImageTag = $Version
        if [[ $IsBeta = "True" ]]; then
          ImageTag = "$Version-beta"
        fi
        echo "##vso[task.setvariable variable=ImageTag]$ImageTag"
        echo "ImageTag: $ImageTag"
      displayName: Compute image tag
      env:
        IsBeta: ${{ ne(variables['Build.SourceBranch'], 'refs/heads/master') }}
        Version: $(version)

    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
