name: $(Date:yyyyMMdd)-$(Rev:rrr)

trigger:
- master

resources:
- repo: self

variables:
  dockerRepository: poveilleux5/azure-file-share-explorer
  version: 0.0.2

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - script: |
        echo "IsMaster: $IsMaster"
        echo "Version: $Version"
        ImageTag="$Version-beta"
        if [[ $IsMaster = "False" ]]; then
          ImageTag="$Version-build-$BuildNumber"
        fi
        echo "##vso[task.setvariable variable=ImageTag]$ImageTag"
        echo "ImageTag: $ImageTag"
      displayName: Compute image tag
      env:
        BuildNumber: $(Build.BuildNumber)
        IsMaster: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}
        Version: $(version)

    - task: Docker@2
      displayName: Build and push $(dockerRepository)
      inputs:
        command: buildAndPush
        containerRegistry: DockerHub
        repository: $(dockerRepository)
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        tags: $(ImageTag)
    
    - script: |
        helm init --client-only
        helm package azure-file-share-explorer --destination $(Pipeline.Workspace) --app-version $(ImageTag)
      displayName: Package helm chart
      workingDirectory: chart/

    - task: PublishPipelineArtifact@1
      displayName: Publish artifacts
      inputs:
        targetPath: $(Pipeline.Workspace)
        artifact: drop
