name: $(Date:yyyyMMdd)-$(Rev:rrr)

trigger:
- master

resources:
- repo: self

# parameters:
# - name: PushBeta
#   displayName: Push beta image to container registry
#   type: boolean
#   defaultValue: false
# - name: IsRelease
#   displayName: Release candidate
#   type: boolean
#   defaultValue: false

variables:
  DockerRepository: poveilleux/azure-file-share-explorer
  Version: 1.0.0
  IsMaster: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - script: |
        echo "IsMaster: $IsMaster"
        echo "Version: $Version"
        echo "IsRelease: $IsRelease"
        ImageTag="$Version-beta"
        if [[ ${IsMaster,,} = "false" ]]; then
          ImageTag="$Version-build-$BuildNumber"
        elif [ ${IsRelease,,} = "true" ]; then
          ImageTag="$Version"
        fi
        echo "ImageTag: $ImageTag"
        echo "##vso[task.setvariable variable=ImageTag]$ImageTag"
      displayName: Compute image tag
      env:
        BuildNumber: $(Build.BuildNumber)
        IsMaster: $(IsMaster)
        Version: $(Version)
        IsRelease: $(IsRelease)

    - task: Docker@2
      displayName: Build $(DockerRepository)
      inputs:
        command: build
        containerRegistry: DockerHub
        repository: $(DockerRepository)
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        tags: $(ImageTag)

    - task: Docker@2
      condition: and(succeeded(), eq(variables['PushBeta'], true))
      displayName: Push $(DockerRepository)
      inputs:
        command: push
        containerRegistry: DockerHub
        repository: $(DockerRepository)
        tags: $(ImageTag)
    
    - script: |
        helm init --client-only
        helm package azure-file-share-explorer --destination $(Build.ArtifactStagingDirectory) --app-version $(ImageTag)
      displayName: Package helm chart
      workingDirectory: chart/

    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: drop
