name: $(Date:yyyyMMdd)-$(Rev:rrr)

trigger:
- master

resources:
- repo: self

variables:
  DockerRepository: poveilleux5/azure-file-share-explorer
  Version: 0.0.2
  IsMaster: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - script: |
        echo "IsMaster: $IsMaster"
        echo "Version: $Version"
        ImageTag="$Version-beta"
        if [[ $IsMaster = "False" ]]; then
          ImageTag="$Version-build-$BuildNumber"
        fi
        echo "##vso[task.setvariable variable=ImageTag]$ImageTag"
        echo "ImageTag: $ImageTag"
      displayName: Compute image tag
      env:
        BuildNumber: $(Build.BuildNumber)
        IsMaster: $(IsMaster)
        Version: $(Version)

    - task: Docker@2
      displayName: Build $(DockerRepository)
      inputs:
        command: build
        containerRegistry: DockerHub
        repository: $(DockerRepository)
        dockerfile: $(Build.SourcesDirectory)/Dockerfile
        tags: $(ImageTag)

    - task: Docker@2
      condition: and(succeeded(), eq(variables['IsMaster'], true))
      displayName: Push $(DockerRepository):$(ImageTag)
      inputs:
        command: push
        containerRegistry: DockerHub
        repository: $(DockerRepository)
        tags: $(ImageTag)
    
    - script: |
        helm init --client-only
        helm package azure-file-share-explorer --destination $(Build.ArtifactStagingDirectory) --app-version $(ImageTag)
      displayName: Package helm chart
      workingDirectory: chart/

    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: drop
