apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azure-file-share-explorer.fullname" . }}
  labels:
{{ include "azure-file-share-explorer.labels" . | indent 4 }}
data:
  appsettings.from-deployment.json: |-
    {{ .Values.appsettings | toJson }}
