apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-file-share-explorer.fullname" . }}
  labels:
{{ include "azure-file-share-explorer.labels" . | indent 4 }}
stringData:
  appsettings.from-secret.json: |-
    {
      "storage": {
        "connectionString": {{ required ".Values.secretValues.storage.connectionString is required" .Values.secretValues.storage.connectionString | quote }},
        "shareName": {{ required ".Values.secretValues.storage.shareName is required" .Values.secretValues.storage.shareName | quote }}
      },
    {{- if .Values.appsettings.azureAd.enabled }}
      "azureAd": {
        "clientId": {{ required ".Values.secretValues.azureAd.clientId is required" .Values.secretValues.azureAd.clientId | quote }},
        "clientSecret": {{ required ".Values.secretValues.azureAd.clientSecret is required" .Values.secretValues.azureAd.clientSecret | quote }}
      }
    {{- end }}
    }
