apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-file-share-explorer.fullname" . }}
  labels:
{{ include "azure-file-share-explorer.labels" . | indent 4 }}
stringData:
  appsettings.from-secret.json: |-
    {
      "storage": {
        "connectionString": {{ required ".Values.secretValues.storage.connectionString is required" .Values.secretValues.storage.connectionString | quote }},
        "shareName": {{ required ".Values.secretValues.storage.shareName is required" .Values.secretValues.storage.shareName | quote }}
      },
      "openIdConnect": {
        "clientId": {{ required ".Values.secretValues.openIdConnect.clientId is required" .Values.secretValues.openIdConnect.clientId | quote }},
        "clientSecret": {{ required ".Values.secretValues.openIdConnect.clientSecret is required" .Values.secretValues.openIdConnect.clientSecret | quote }}
      }
    }
