apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-file-share-explorer.fullname" . }}
  labels:
{{ include "azure-file-share-explorer.labels" . | indent 4 }}
stringData:
  appsettings.from-secret.json: |-
    {{ .Values.secretValues | toJson }}
