apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-file-share-explorer.fullname" . }}
  labels:
{{ include "azure-file-share-explorer.labels" . | indent 4 }}
stringData: |-
  {
    "storage": {
      "connectionString": {{ required ".Values.secretValues.storage.connectionString is required" .Values.secretValues.storage.connectionString | quote }},
      "shareName": {{ required ".Values.secretValues.storage.shareName is required" .Values.secretValues.storage.shareName | quote }}
    },
    "azureAd": {{ .Values.secretValues.azureAd | toJson }}
  }
