{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "azure-file-share-explorer.serviceAccountName" . }}
  labels:
{{ include "azure-file-share-explorer.labels" . | indent 4 }}
{{- end -}}
